version: '3'
services:
  kafka-ui:
    # restart: always
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka1
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
    # volumes:
    #   - config.yml:/etc/kafkaui/dynamic_config.yaml
  zookeeper:
    image: docker.io/wurstmeister/zookeeper
    container_name: zookeeper
    # restart: always
    ports:
      - "2181:2181"

  kafka1:
    image: docker.io/wurstmeister/kafka
    container_name: kafka1
    # restart: always
    ports:
      - "9095:9092"
    depends_on:
      - zookeeper
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9095

  kafka2:
    image: docker.io/wurstmeister/kafka
    container_name: kafka2
    # restart: always
    ports:
      - "9096:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9096

  kafka3:
    image: docker.io/wurstmeister/kafka
    container_name: kafka3
    # restart: always
    ports:
      - "9097:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9097

  go:
    image: golang:1.20
    container_name: go
    # restart: always
    volumes:
      - ./go:/workspace
    stdin_open: true
    tty: true
    working_dir: /workspace
      